version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
  # db:
  #   image: postgres
  #   environment:
  #     POSTGRES_DB: mydb
  #     POSTGRES_USER: myuser
  #     POSTGRES_PASSWORD: mypassword
